### ISSUE TITLE
Refuses to boot

### ISSUE THREAD

**Issue by Velocikitty** [Wurielle/izabela-desktop#13]
I have no clue how this broke now.

https://i.imgur.com/hLU9u3W.png

**Comment by Wurielle** [comment]
Can you try deleting the analytics folder in `C:\Users\Kitty\AppData\Roaming\Izabela` and restart the application? After the restart it should recreate the folder. 
Did you modify the file within the analytics folder or did you have a Windows update recently maybe?

**Comment by Velocikitty** [comment]
Yeah, there was one the other day. I hadn't been using it.

Gimme a sec to try to get it to boot now and I'll edit in if it worked.

**Comment by Wurielle** [comment]
Thanks for the edit! I was using google analytics to report exceptions because I didn't know better at the time but I found a much better solution now and I'm planning to implement it with the reworked version of the app. It should also fix this random bug.

Also sorry if it's taking long between versions but I'm working on it on my free time and it's sometimes challenging. It's definitely coming out though! Thanks for the help on the project! 👍

**Comment by Velocikitty** [comment]
No worries. Its damned good, and the fact you are even supporting it still is awesome.

It fits everything I ever needed, and with some tweaks, I can see it being even more useful, at least to myself!

You also reply to issues really fast too.

**Comment by Wurielle** [comment]
Fixed since [v0.6.0](https://github.com/Wurielle/izabela-desktop/releases/latest).
