### ISSUE TITLE
Add option to toggle app minimized on startup

### ISSUE THREAD

**Issue by Chewdogga** [Wurielle/izabela-desktop#14]
On my computer Izabela starts only as a background task. Is Izabela supposed to start up with the settings/options page? From the instructions it seemed like the settings page was supposed to start automatically on the app's startup.

Can someone please post a user-settings file that is connected to virtual audio cables since I cannot access the settings/options page?

Thanks for your time!

**Comment by Wurielle** [comment]
Hello @Chewdogga! Yes this is intended, Izabela starts in the background so that it's ready to be used as soon as you're in window. 

To open the app manually click on the little icon in the icon bar in the bottom right of your task bar:
![image](https://user-images.githubusercontent.com/15323067/58402265-2d7ea100-8060-11e9-83b1-95a8d1ec36ea.png)

This will open the main interface and you'll be able to access the settings with this icon:
![image](https://user-images.githubusercontent.com/15323067/58402493-c31a3080-8060-11e9-9c3a-bf8647993ae7.png)

In the future you'll be able to choose whether the app should start in the background or not and there will be a notification to tell you that it has been started in the background.

**Comment by Chewdogga** [comment]
Thanks you! LOL I can't believe I missed that.

**Comment by Wurielle** [comment]
No worries! I know it's not the ideal way to start the app for sure so I'm planning to give a proper option to choose whether or not the app should start as minimized. I'll update the title to keep it in mind and close this when an update for it is released.

**Comment by Wurielle** [comment]
There will be an option to start the application as minimized in the next version 👍

**Comment by Wurielle** [comment]
Feature added in [v0.6.0](https://github.com/Wurielle/izabela-desktop/releases/latest).
