### ISSUE TITLE
Using installed/SAPI5 voices?

### ISSUE THREAD

**Issue by igotbackpain** [Wurielle/izabela-desktop#15]
I use a few voices that I've installed from other places, such as IVONA or Cepstral, but I can't seem to use the voices in Izabela. It'd be nice to be able to use the ones that I have already installed.

**Comment by Wurielle** [comment]
Heya @igotbackpain ! Izabela uses services packaged within the app making external services very hard to integrate.
However IVONA seems to have been replaced by Amazon Polly and I do plan to give an option to use Amazon Polly.

The current plan is to integrate Google Cloud's Text-To-Speech first and from that I'll be able to integrate Amazon Polly without a hasle (I hope).

My hope for a version that includes the reworked app and the Google Cloud API is for late July/ early August if everything goes to plan.

If you'd like you could list all services you'd like to see included and I could take a look at each individually and see if I can do something to put them in the application over time. 👍 

On a side note it's funny how I just started having back pain since a few days ago, I hope you're not responsible for it! But take care if you happen to have some too haha.

**Comment by Wurielle** [comment]
In 0.10.0 I added an API called "Say" which should let you use voices installed on your system. Let me know if this works for you! 👍

**Comment by camjac251** [comment]
Hey. I was wondering if this still works for you in the current Windows version 20H2. I installed Ivona Brian and tested it inside of the Windows Narrator (it shows up for personalize narrator voice but not under speech settings)
![image](https://user-images.githubusercontent.com/6313132/101201734-d337a680-362d-11eb-80ee-93db5047f371.png)
![image](https://user-images.githubusercontent.com/6313132/101201748-d7fc5a80-362d-11eb-959a-1b1af9d0e6ea.png)

If I set it to default it uses the Speech default I believe but when I set it to Brian, I hear nothing back after trying it out. Would you be interested in debug logs?

**Comment by camjac251** [comment]
Amazing work on adding Google Cloud TTS. I am worried though that it might not be sustainable financially with everyone using. I plan on chipping in hopefully in the next few days. Are you open to allowing the user to input their own API key for a google cloud project with the cloud tts api? I use izabela quite heavily and it would be nice to be able to separate usage from everyone else, making it cost less for you.

**Comment by Wurielle** [comment]
> Amazing work on adding Google Cloud TTS. I am worried though that it might not be sustainable financially with everyone using. I plan on chipping in hopefully in the next few days. Are you open to allowing the user to input their own API key for a google cloud project with the cloud tts api? I use izabela quite heavily and it would be nice to be able to separate usage from everyone else, making it cost less for you.

Thank you for your concern! I plan to watch the monthly use of the api and see whether or not the cost stays within the free tier range. If not I don't mind paying for a few months and see how much it costs me. I will only remove the API if it costs me way more than expected but I plan to indeed make another software that lets you host your own TTS APIs with easy steps to set it up eventually. 😄

**Comment by camjac251** [comment]
> 
> 
I will only remove the API if it costs me way more than expected but I plan to indeed make another software that lets you host your own TTS APIs with easy steps to set it up eventually. 😄


The API for Google Cloud TTS is on their side. When you say own TTS APIs do you mean fully self hosted or just, using API keys from Google Cloud Platform's API console.

I was hoping to put in my own key in the settings somewhere to use my own Google Cloud Platform project
![Izabela_2021-05-26_20-12-55](https://user-images.githubusercontent.com/6313132/119752502-c0768f80-be62-11eb-8adc-a2abe89531e7.png)

**Comment by Wurielle** [comment]
Google Cloud services don't use API keys, they use a config file that needs to be present at runtime for their modules. The issue is that the location of the file needs to be set in the PATH and the modules don't work in electron's process (in Izabela at least). 

I created a remote server that uses these modules because it's the way it's meant to used and it's easier to maintain on my end.

To achieve what you want I'd have to create a separate application and can't just implement it within Izabela. It's on my list of things to do though.

**Comment by camjac251** [comment]
Are we thinking of the same thing? I've used another tool recently that was a web extension for Chrome and its input was a simple API key generated

**Comment by Wurielle** [comment]
I searched the source code for that chrome plugin and it uses GC's rest API which is not exactly what I used for Izabela GCTTS BUT the way I implemented it in Izabela would make it very easy to switch between the 2 by just adding an API key like in your example.

I created another issue for that feature here: #62. I don't have an ETA but it should be an easy feature. 
It's a very good alternative in case I can't keep the server up due to financial issues. Thanks for the help!

**Comment by camjac251** [comment]
Oh sweet. Looking forwards to seeing the progression of Izabela. It's been a go to for me almost every day.

I was curious if you've seen the earlier reply I posted back in December in this issue about a bug I had with getting a SAAPI voice to work inside of Izabela. Would it be possible if I can send you the SAAPI voice that I tried. After selected it inside of Izabela and typing in a sentence to run, it wouldn't output and I think got stuck since switching to Responsive Voice afterward and typing a new sentence didn't output anything either until I full restarted the app.
