### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by matusli** [Wurielle/izabela-desktop#20]
Hello, its me again. 

i've updated from 5.7 to 6.2 and i've noticed a massive performance drop (?), typing has a delay and even sometimes swaps letters, and the greytext seems to stutter between choosing a phrase, might be connected. all in all the responsibility of the program decreased which is in intense situations in games a huge problem, i'll be rollbacking to 5.7

hopefully it is just a loop bug in the text hints

**Comment by Wurielle** [comment]
Hello @matusli.

Sorry to hear you're having theses issues. I don't have recommended specs for the software as of now but with the 0.6.0 release I made sure to improve performances with versions 0.6.0 and up so that shouldn't be happening.

Do you mind sharing your PC specifications to help me with the case?

**Comment by matusli** [comment]
Hi there,

I doubt it is my pc - i7 9800, 1050 , 16gigs of 3200 mem.

To elaborate, upon pressing the keys alt enter, it takes a moment longer to load, and while i can still type, it'll show up a second later. If i do not type, the random grey message seems to switch many times for a second or two before the program resumes usual performance. The amount of the swaps is seemingly random and it sometimes doesnt do this at all, but im reading HUGE cpu usage (25%) for the moment if it does mess up

**Comment by Wurielle** [comment]
Hello @matusli! Very sorry for the late answer..

I just released a new build to address some performance issues with the overlay mode.
I couldn't reproduce the latency myself so I did as best as I can to try to optimize some parts of that feature.

If you don't mind sharing, are you using a HDD, SHDD, SSD or something else as primary drive? Also were you using windows 10 when it happened? That could help me find where the issue comes from.

Please let me know if the [latest build](https://github.com/wurielle/izabela-desktop/releases/tag/v0.7.0) solves the issue for you. If it doesn't I'll keep working on it for the next build.


Thanks again for trying out the software! Hope it helps!

**Comment by Wurielle** [comment]
I released a build ([0.9.0](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.9.0)) which includes more performance improvements regarding the overlay. Let me know if it fixed the issue for you!
