### ISSUE TITLE
Voices

### ISSUE THREAD

**Issue by Abigao** [Wurielle/izabela-desktop#22]
New build seems nice but i am still using 5.7 due to the voice options not working in the newer builds for me, even in 5.7 not all work but the ones that do sound a lot better than the weird one i have for the other 2, Also the hotkey option is still causing me  problems in some games toggling full screen and windowed mode.

**Comment by Wurielle** [comment]
Hello @Abigao! Thanks for reporting the issue!

I'll try to take a look soon at the voices not working. Can you list me those you are using so that I can prioritize them? 

I'm still trying to figure out how to create custom hotkeys so hopefully that won't be an issue in the future. In the meantime you can try to launch the application as administrator as it is known to sometimes allow the application to take priority over other softwares. I know it did the trick for me in Killing Floor 2 but I didn't test with a lot of other games/softwares.

To enable the option right click on the Izabela icon on your taskbar and right click again on the Izabela icon showing up:
![image](https://user-images.githubusercontent.com/15323067/73218932-41cced80-415b-11ea-988c-742a2ca6882a.png)

Then go to the compatibility tab and check "Run this program as an administrator". And restart the application.
![image](https://user-images.githubusercontent.com/15323067/73218851-121de580-415b-11ea-83a9-78733a643e24.png)

Let me know if it helped! And thanks again for trying out the software!

**Comment by Abigao** [comment]
Admin seems to work, will let you know if it doesnt!
The Australian female, and Dutch voices are my most used, thanks for the quick responce!

**Comment by Wurielle** [comment]
I managed to fix almost all voices over the weekend. The ones you are using are working fine now. 
I also added a very basic way to change the key binding for overlay mode. You won't be able to bind every single key there is in existence but you'll still have a lot options available.

I'll try to make a build in the evening once I double check that everything is working. 👍

**Comment by Wurielle** [comment]
The update is live! You can access all these new features in the [0.8.0 version](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.8.0)!

**Comment by Abigao** [comment]
Ah so far it seems amazing, thank you so much! and no more fighting with random games over the shortcut! What a god This means a lot to me thank you thank you!

**Comment by Wurielle** [comment]
My pleasure! 👍 

Let me know if you need any other features!
