### ISSUE TITLE
Typing and backspacing is delayed

### ISSUE THREAD

**Issue by Mayruii** [Wurielle/izabela-desktop#24]
When you backspace and type in the overlay it slows down a ton. The delay in backspacing also cycles through the weird grey built in quotes and basically makes it impossible to type for a few seconds. Seems to eat up some cpu too.

**Comment by Wurielle** [comment]
Hello @Mayruii! Thanks for reporting the issue!

This might be linked to #20. I'll take a look into it this week and see if I can improve performances. 
Sorry for the inconvenience.

**Comment by Wurielle** [comment]
I'm working on a fix for it which will also include some more performance improvements here and there so the application should overall be more responsive.

**Comment by Wurielle** [comment]
I released a build ([0.9.0](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.9.0)) which includes a lot of performance improvements. Please let me know if it solves the issue for you! 👍

**Comment by Abigao** [comment]
The input lag is back for me on this build, I can't speak without typing very slowly, Also could you set auto update to off by default, it was very hard to go back to 0.8.0

**Comment by Mayruii** [comment]
Same for me, input lag is still there and almost unusable for me with 0.9.0

**Comment by Wurielle** [comment]
Mhh this is very odd since 0.9.0 is the most optimized build so far regarding overlay mode and the app in general. 

Do you have other CPU/Memory heavy softwares (Games, Editing Softwares, ...)  running when this occurs?
Does this happen right after installation? If yes, is there an antivirus scanning your files?
Can you give me some of your PC specs?

To answer @Abigao, I won't disable auto updates by default in case there are some issues that need to be hotfixed but if you want to stick to a version in particular you can let it download the lastest version then go to the settings and disable auto update there then install a previous version and it should keep the settings from the newest version without automatically downloading the new one. This will work for any versions after 0.6.0.

**Comment by Abigao** [comment]
No antivirus, and nothing open besides the  program, even after rebooting. Was immediate and stopped as soon as i went back to 0.8.0

**Comment by Wurielle** [comment]
I actually found where the issue is coming from with a lot of luck.. It's gonna sound very ironic but if you have this option disabled, then it will start lagging.
![image](https://user-images.githubusercontent.com/15323067/74112564-19eb7a00-4b9e-11ea-99dc-16bb08a6fde6.png)
Maybe it's not the only factor so I'll keep digging for more but I managed to reproduce this issue 100% of the time on several devices just by toggling this option only.

To be fair I have no idea why that would make the overlay input lag at all.. I'll try to fix the issue during the week. Sorry about that.

**Comment by Wurielle** [comment]
I just released [0.9.1](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.9.1) which should fix that issue for good and hopefully let me sleep on both ears at night.

**Comment by matusli** [comment]
10.0 seems like the issue is fixed! thank you a ton for your continued support!

**Comment by Wurielle** [comment]
🎉 Yay! My pleasure! Thank you for helping me with the project!
