### ISSUE TITLE
Can only say hello

### ISSUE THREAD

**Issue by Abigao** [Wurielle/izabela-desktop#25]
out of no where, all inputs besides  saying "hello" by itself are not being spoken, i've tried rolling back the  build an its still happening, cant use this at all anymore. Have deleted all files an tried reinstalling fresh too. Not really sure whats happened.

**Comment by Abigao** [comment]
update: "say" works fine, only responsive voice is affected

**Comment by ArcAngelica** [comment]
Same issue here, I thought it was related to recent Windows Updates that happened 2 days ago and more updates yesterday, but rolling back did not fix this problem

Reponsive voices for me don't work at all, I didn't try every language but I know that US Female is completely broken, and UK Female can only say Hello and Test

This issue is 2 days recent at best, cause I've recorded the TTS working fine as of yesterday

**Comment by Wurielle** [comment]
Responsive Voice may have updated their API, I'll take a look into it tonight.

In the meantime you can use the "Say" API. Since it uses your system's voices it will never break randomly.

Sorry for the inconvenience.

**Comment by Mayruii** [comment]
Experiencing the same issue and Say doesn't work for me. I type stuff in and nothing happens, been happening before the responsive voice breaking.

**Comment by Wurielle** [comment]
It should be working again in [0.10.1](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.10.1). 👍 

This might happen again in the future since I have no power over when they decide to change their structure. I might implement other APIs soon to make sure that at least one of them is up at all time.

**Comment by Wurielle** [comment]
> Experiencing the same issue and Say doesn't work for me. I type stuff in and nothing happens, been happening before the responsive voice breaking.

@Mayruii Do you have voices listed in "Say" like so:
![image](https://user-images.githubusercontent.com/15323067/74585797-2e39d780-4fe1-11ea-866f-c3ed719522d8.png)

**Comment by Mayruii** [comment]
Yes I do. I changed to the Say and tested every voice I have. None work and when changing back to responsive voice the same thing happens until I close and open it.

**Comment by Wurielle** [comment]
@Mayruii I'll create another issue for your specific case as it is not related to this one. I may have some ideas on why that's the case. I'll share more informations on the new issue.
