### ISSUE TITLE
0.12.0 seems to be completely broken

### ISSUE THREAD

**Issue by Velocikitty** [Wurielle/izabela-desktop#44]
I can only use it once, and then have to open the program via the task bar.

**Comment by Velocikitty** [comment]
Seems to reset only if you swap the keybinds for it, but again, only once.

**Comment by Velocikitty** [comment]
Fresh install does not seem to help it. Works once, then back to the same issue.

**Comment by Velocikitty** [comment]
Video showing the bug in action: https://www.youtube.com/watch?v=Fa-3xpmFPls

**Comment by Wurielle** [comment]
Hello @Velocikitty! Thanks a bunch for the video and it helped me understand the issue.

Due to the way the new overlay works, every keys mapped with `shift`, `alt`, `altGr` will have a conflict with the overlay toggle keybinding option it seems..

Try to disable Auto Update and downgrade to v0.11.0 until I find a solution or add `ctrl` to toggle your overlay with `ctrl` + `alt` + `q`

**Comment by Wurielle** [comment]
I'm working on a solution for your case but there will be a lot of edge cases where this issue might happen again.

This happens due to a conflict between all global shortcuts from the application and shortcuts created (then removed) by the overlay.

It can be fixed by creating a warning when creating a shortcut within the application in order to warn the user that a shortcut is already in use or prevent the closing of the overlay by pressing the overlay shortcut again (not ideal).

I'll test the fix for your issue when I get home and see if it's ready for release in the following days.

**Comment by Velocikitty** [comment]
Alright!

**Comment by Wurielle** [comment]
Should be fixed with [v0.12.1](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.12.1)

**Comment by Velocikitty** [comment]
Can confirm it is working!
