### ISSUE TITLE
Inconsistant voicing.

### ISSUE THREAD

**Issue by FlufflesTheDog** [Wurielle/izabela-desktop#7]
The voice used appears to change randomly with some sentences, saying the same words in a completely different tone or accent, This started happening for both myself and a friend, without any changes to the app; neither deleting Izabela's appdata folder or a complete reinstall appear to influence the issue.

**Comment by Wurielle** [comment]
Hey @FlufflesTheDog, this is unfortunately an issue related more to the Voice API I am using rather than the app itself. I have no control over it sadly.

However I plan to implement new services that are better in quality such as Google Cloud's Text-to-Speech. I'm still thinking on ways to implement it but I'm going to implement it for sure!

**Comment by FlufflesTheDog** [comment]
Okay, thank you for the reply and your work.
Hope you're able to figure something out!

**Comment by Wurielle** [comment]
Should be fixed with [v0.10.3](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.10.3). Feel free to reopen if that's still occuring.
