### ISSUE TITLE
Ability for it to press other keys

### ISSUE THREAD

**Issue by Velocikitty** [Wurielle/izabela-desktop#8]
So that you can use this with PTT required games/settings.

**Comment by Wurielle** [comment]
Hi @Velocikitty , can you enlighten me on how that would work? Since you have to use your keyboard to type in global mode, wouldn't it be impractical to hold the PTT while typing?

I definitely would like to implement something that would allow you to bind custom keys however.

**Comment by Velocikitty** [comment]
Basically, just a way that it can hold down a key when it speaks.

Like say I have my PTT key bound to num pad 0. I can type what I want, then press enter, and it'll hold Zero down, and then say it, then release it. (Maybe even do something like shift + enter = PTT bind?)

Used to use VoiceAttack to do so with predefined macros, but this actually lets me speak semi-fluently (Only lag is typing it out)

Also re-bindable keys would be nice period.

**Comment by k9lego** [comment]
I wrote a duplicate issue about a feature like this. This would be particularly helpful, having the ability to tell it to bind a key and hold it. Here's how it could work:
1 - The program holds down the key combination and is programmed to ignore that key combo in the typing box.
2 - It sends a key hold down message to the OS and somehow that is bypassed by the program (not sure if this is possible, probably isn't).

**Comment by Velocikitty** [comment]
Right now, I just use VoiceAttack (Ha-ha considering mute, but its what I used for my old macro based TTS.) to keep the mic open. Its annoying and I have to reset it any time I alt tab but it works.

https://i.imgur.com/vScKbXS.png

Somehow VA has managed to get it hooked in that you can type fully without issues (Its not just holding the two buttons down at all. Its toggling them.

Its a work around, and it pisses some people off till I say "You won't hear anything from me until I type in, its just the way I have to do it for now."

**Comment by Wurielle** [comment]
You can bind custom keys  since [v0.8.0](https://github.com/Wurielle/izabela-desktop/releases/latest) (see #22).

**Comment by Velocikitty** [comment]
That wasn't the issue, but it is welcome.

I meant when it is outputting the voice, it can hold buttons down (To allow you to use something other than Voice Activation.)

**Comment by Wurielle** [comment]
I made some progress on that feature and I am allowed to make the application hold down a combination of keys. I will set the default key to F8 since it usually allows you to still type while it's being held.

One thing you should know is that not all combinations will work as you'd expect. For instance, if `Ctrl` + `Shift` is your PTT combo and you send a message, it will hold these 2 keys correctly but if you attempt to type while these keys are being held, you won't receive any inputs into the overlay's text area. The reason being: let's say we want to press the letter `A` and the `Ctrl` + `Shift` combo is held, the system will actually send `Ctrl` + `Shift` + `A`. This is not something I am planning to fix as it is expected behavior for the system. 

However some keys actually let you use any other keys while being held. `F8` is one of them so `F8` + `A` will just send `A`. For that reason I recommend changing the PTT keys in the softwares you're planning to use the feature in rather than changing the key binding within the application (even though you'll be able to if you want to experiment).

Also some other points worth to mention:
* You will have to have [Java](https://www.java.com/en/) installed for the feature to work. 
* Using this feature, audio outputs will be delayed by about half a second. It's barely noticeable however and you'll still be able to disable the feature to have the regular experience. The feature will be disabled by default.

I still need to make some tests before releasing the feature but you could potentially expect something in the following weeks.

**Comment by Velocikitty** [comment]
Sadly, I think that means TFAR (A mod for ARMA that mimics actual Radios, and uses a combo of a in game mod and TS3), won't work, but should work for other PTT games.

But that sounds awesome. Thanks for the continued support on this thing. its bloody awesome <3

**Comment by Wurielle** [comment]
It should still work for TFAR I think. The only problem you'll face is that you'll have to wait for the voice to be done before you can type anything else. Otherwise it would work just fine.

I decided to release a build [(0.9.0)](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.9.0) with the feature so you can try it out for yourself.

Thank you for supporting the project and giving your feedback! 👍
